data:
  dataset: banknote_authentication
  dataset_path: configs/banknote_authentication/dataset.csv
  target_column: class
experiment:
  tags:
  - banknote_authentication
  name: banknote_authentication
model:
  type: RandomForestClassifier
  n_estimators: 12
  min_samples_split: 2
  min_impurity_decrease: 0.0
  max_features: null
  max_depth: 7
  criterion: entropy
