data:
  dataset: bank_marketing
  dataset_path: configs/bank_marketing/dataset.csv
  target_column: y
  separator: ;
  categorical_features:
  - job
  - marital
  - education
  - default
  - housing
  - loan
  - contact
  - month
  - day_of_week
  - poutcome
experiment:
  tags:
  - bank_marketing
  name: bank_marketing
methods:
  _default:
    actionability:
      age: non_decreasing
      job: actionable
      marital: actionable
      education: actionable
      default: no_change
      housing: actionable
      loan: actionable
      contact: actionable
      month: actionable
      day_of_week: actionable
      duration: non_decreasing
      campaign: non_decreasing
      pdays: non_decreasing
      previous: non_decreasing
      poutcome: actionable
      emp.var.rate: actionable
      cons.price.idx: actionable
      cons.conf.idx: actionable
      euribor3m: actionable
      nr.employed: actionable
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_impurity_decrease: 0.0
  max_features: null
  max_depth: 5
