data:
  dataset: sick_euthyroid
  dataset_path: configs/sick_euthyroid/dataset.csv
  target_column: target
experiment:
  tags:
  - sick_euthyroid
  name: sick_euthyroid
methods:
  _default:
    actionability:
      0: non_decreasing
model:
  type: RandomForestClassifier
  n_estimators: 20
  min_samples_split: 3
  min_impurity_decrease: 0.0
  max_features: 0.7
  max_depth: 10
  criterion: entropy
