data:
  dataset: quality_control_dataset
  dataset_path: configs/quality_control_dataset/dataset.csv
  target_column: Defective
experiment:
  tags:
  - quality_control_dataset
  name: quality_control_dataset
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_samples_split: 10
  min_impurity_decrease: 0.01
  max_features: 0.7
  max_depth: 3
  criterion: gini
