data:
  dataset: webpage
  dataset_path: configs/webpage/dataset.csv
  target_column: target
experiment:
  tags:
  - webpage
  name: webpage
model:
  type: RandomForestClassifier
  n_estimators: 15
  min_samples_split: 4
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 10
  criterion: gini
