data:
  dataset: diabetes
  dataset_path: configs/diabetes/dataset.csv
  target_column: Outcome
experiment:
  tags:
  - diabetes
  name: diabetes
model:
  type: RandomForestClassifier
  n_estimators: 12
  min_samples_split: 12
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 8
  criterion: entropy
