data:
  dataset: diabetes
  dataset_path: configs/diabetes/dataset.csv
  target_column: Outcome
experiment:
  tags:
  - diabetes
  name: diabetes
methods:
  _default:
    actionability:
      Age: non_decreasing
      Pregnancies: non_decreasing
      DiabetesPedigreeFunction: no_change
      BMI: actionable
      Glucose: actionable
      BloodPressure: actionable
model:
  type: RandomForestClassifier
  n_estimators: 12
  min_samples_split: 12
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 8
  criterion: entropy
