data:
  dataset: energy_dataset
  dataset_path: configs/energy_dataset/dataset.csv
  target_column: Anomalous
experiment:
  tags:
  - energy_dataset
  name: energy_dataset
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_samples_split: 10
  min_impurity_decrease: 0.01
  max_features: null
  max_depth: 5
  criterion: entropy
