data:
  dataset: ecoli
  dataset_path: configs/ecoli/dataset.csv
  target_column: target
experiment:
  tags:
  - ecoli
  name: ecoli
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_samples_split: 12
  min_impurity_decrease: 0.0
  max_features: 0.5
  max_depth: 4
  criterion: gini
