data:
  dataset: german_credit
  dataset_path: configs/german_credit/dataset.csv
  target_column: foreign_worker
  categorical_features:
  - account_check_status
  - credit_history
  - purpose
  - savings
  - present_emp_since
  - personal_status_sex
  - other_debtors
  - property
  - other_installment_plans
  - housing
  - job
  - telephone
experiment:
  tags:
  - german_credit
  name: german_credit
methods:
  _default:
    actionability:
      age: non_decreasing
      personal_status_sex: no_change
model:
  type: RandomForestClassifier
  n_estimators: 7
  min_samples_split: 4
  min_impurity_decrease: 0.0
  max_features: 0.5
  max_depth: 7
  criterion: entropy
