data:
  dataset: customer_personality_analysis
  dataset_path: configs/customer_personality_analysis/marketing_campaign.csv
  target_column: Response
  separator: "\t"
  categorical_features:
  - Education
  - Marital_Status
experiment:
  tags:
  - customer_personality_analysis
  name: customer_personality_analysis
methods:
  _default:
    actionability:
      ID: no_change
      Year_Birth: no_change
      Education: actionable
      Marital_Status: actionable
      Income: actionable
      Kidhome: non_decreasing
      Teenhome: non_decreasing
      Dt_Customer: no_change
      Recency: non_decreasing
      MntWines: actionable
      MntFruits: actionable
      MntMeatProducts: actionable
      MntFishProducts: actionable
      MntSweetProducts: actionable
      MntGoldProds: actionable
      NumDealsPurchases: actionable
      NumWebPurchases: actionable
      NumCatalogPurchases: actionable
      NumStorePurchases: actionable
      NumWebVisitsMonth: actionable
      AcceptedCmp3: no_change
      AcceptedCmp4: no_change
      AcceptedCmp5: no_change
      AcceptedCmp1: no_change
      AcceptedCmp2: no_change
      Complain: no_change
      Z_CostContact: no_change
      Z_Revenue: no_change
      Response: no_change
model:
  type: RandomForestClassifier
  n_estimators: 15
  min_samples_split: 10
  min_impurity_decrease: 0.01
  max_features: 0.4
  max_depth: 6
  criterion: entropy
