data:
  dataset: oil
  dataset_path: configs/oil/dataset.csv
  target_column: target
experiment:
  tags:
  - oil
  name: oil
experiment_params:
  sample_indices:
  - 4
output:
  save_visualizations: true
  save_visualization_images: true
model:
  type: RandomForestClassifier
  n_estimators: 4
  min_samples_split: 3
  min_impurity_decrease: 0.0
  max_features: 0.7
  max_depth: 4
  criterion: entropy
