data:
  dataset: heart_disease_uci
  dataset_path: configs/heart_disease_uci/dataset.csv
  target_column: num
  categorical_features:
  - sex
  - dataset
  - cp
  - restecg
  - slope
  - thal
experiment:
  tags:
  - heart_disease_uci
  name: heart_disease_uci
model:
  type: RandomForestClassifier
  n_estimators: 25
  min_samples_split: 10
  min_impurity_decrease: 0.01
  max_features: 0.3
  max_depth: 5
  criterion: entropy
