data:
  dataset: breast_cancer_wisconsin
  dataset_path: configs/breast_cancer_wisconsin/dataset.csv
  target_column: diagnosis
experiment:
  tags:
  - breast_cancer_wisconsin
  name: breast_cancer_wisconsin
model:
  type: RandomForestClassifier
  n_estimators: 15
  min_samples_split: 10
  min_impurity_decrease: 0.01
  max_features: 0.3
  max_depth: 10
  criterion: entropy
