data:
  dataset: coil_2000
  dataset_path: configs/coil_2000/dataset.csv
  target_column: target
experiment:
  tags:
  - coil_2000
  name: coil_2000
model:
  type: RandomForestClassifier
  n_estimators: 10
  min_samples_split: 12
  min_impurity_decrease: 0.0
  max_features: 0.7
  max_depth: 5
  criterion: entropy
