data:
  dataset: satimage
  dataset_path: configs/satimage/dataset.csv
  target_column: target
experiment:
  tags:
  - satimage
  name: satimage
model:
  type: RandomForestClassifier
  n_estimators: 20
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 10
