data:
  dataset: optical_digits
  dataset_path: configs/optical_digits/dataset.csv
  target_column: target
experiment:
  tags:
  - optical_digits
  name: optical_digits
model:
  type: RandomForestClassifier
  n_estimators: 20
  min_samples_split: 5
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 10
  criterion: entropy
