data:
  dataset: abalone
  dataset_path: configs/abalone/dataset.csv
  target_column: target
experiment:
  tags:
  - abalone
  name: abalone
model:
  n_estimators: 7
  type: RandomForestClassifier
  max_depth: 6
  min_impurity_decrease: 0.0
  max_features: 0.5
output:
  save_visualizations: true
  save_visualization_images: true
