data:
  dataset: abalone
  dataset_path: configs/abalone/dataset.csv
  target_column: target
experiment:
  tags:
  - abalone
  name: abalone
model:
  n_estimators: 2
  type: RandomForestClassifier
  max_depth: 3
output:
  save_visualizations: true
  save_visualization_images: true
