data:
  dataset: iris
  dataset_path: configs/iris/dataset.csv
  target_column: target
model:
  type: RandomForestClassifier
  max_depth: 4
  n_estimators: 7
  max_features: 0.5
  min_impurity_decrease: 0.1
experiment:
  tags:
  - iris
  - baseline
  name: iris
  entity: mllab-ts-universit-di-trieste
  notes: Initial baseline run with default parameters
experiment_params:
  requested_counterfactuals: 5
  num_samples: 1
  sample_indices:
  - 2
  max_workers: null
output:
  save_visualizations: true
  save_visualization_images: true
  save_visualizations_per_generation: false
methods:
  _default:
    max_generations: 100
    rules:
    - none
  dpg:
    generation_debugging: true
    diversity_weight: 0.8
