data:
  dataset: arrhythmia
  dataset_path: configs/arrhythmia/dataset.csv
  target_column: target
experiment:
  tags:
  - arrhythmia
  name: arrhythmia
model:
  type: RandomForestClassifier
  n_estimators: 4
  min_samples_split: 12
  min_impurity_decrease: 0.02
  max_features: 0.5
  max_depth: 4
  criterion: entropy
