data:
  dataset: car_eval_4
  dataset_path: configs/car_eval_4/dataset.csv
  target_column: target
experiment:
  tags:
  - car_eval_4
  name: car_eval_4
model:
  type: RandomForestClassifier
  n_estimators: 20
  min_samples_split: 2
  min_impurity_decrease: 0.0
  max_features: null
  max_depth: 10
  criterion: entropy
