# Kaggle dataset: https://www.kaggle.com/datasets/fatemehmehrparvar/obesity-levels
data:
  dataset: obesity_levels
  dataset_path: configs/obesity_levels/dataset.csv
  target_column: NObeyesdad
  categorical_features:
  - Gender
  - CALC
  - FAVC
  - SCC
  - SMOKE
  - family_history_with_overweight
  - CAEC
  - MTRANS
experiment:
  tags:
  - obesity_levels
  name: obesity_levels
methods:
  _default:
    actionability:
      Age: non_decreasing
      Gender: no_change
      Height: no_change
      Weight: actionable
      CALC: actionable
      FAVC: actionable
      FCVC: actionable
      NCP: actionable
      SCC: actionable
      SMOKE: actionable
      CH2O: actionable
      family_history_with_overweight: no_change
      FAF: actionable
      TUE: actionable
      CAEC: actionable
      MTRANS: actionable
model:
  type: RandomForestClassifier
  n_estimators: 4
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 3
